version: '2'

services:
  nginx:
    container_name: NODE_NGINX_LB
    build: ./nginx
    links:
      - app-1:app-1
      - app-2:app-2
      - app-3:app-3
    ports:
      - 3000:80
    depends_on:
      - app-1
      - app-2
      - app-3

  app-1:
    container_name: NODE_NGINX_1
    image: node_nginx:0.0.1
    ports:
      - 3000

  app-2:
    container_name: NODE_NGINX_2
    image: node_nginx:0.0.1
    ports:
      - 3000

  app-3:
    container_name: NODE_NGINX_3
    image: node_nginx:0.0.1
    ports:
      - 3000